app/feedback/models.py
from app import db

class Feedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    message = db.Column(db.Text, nullable=False)

app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    complete = db.Column(db.Boolean, default=False)

    def as_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "completed": self.complete,
        }

app/feedback/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class FeedbackForm(FlaskForm):
    name = StringField('Ім\'я', validators=[DataRequired()])
    message = TextAreaField('Відгук', validators=[DataRequired()])
    submit = SubmitField('Відправити')

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class TodoForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    submit = SubmitField('Save')

app/feedback/__init__.py
from flask import Blueprint

feedback_blueprint = Blueprint('feedback', __name__, template_folder="templates", url_prefix="/feedback")

from . import views

app/feedback/views.py
from flask import render_template, redirect, url_for,  flash
from app import db
from .forms import FeedbackForm
from .models import Feedback
from . import feedback_blueprint


@feedback_blueprint.route('/feedback', methods=['GET', 'POST'])
def feedback():
    form = FeedbackForm()
    if form.validate_on_submit():
        name = form.name.data
        message = form.message.data

        feedback = Feedback(name=name, message=message)
        db.session.add(feedback)
        db.session.commit()
        flash('Ваш відгук був збережений', 'success')
        return redirect(url_for('.feedback'))

    feedbacks = Feedback.query.all()
    return render_template('feedback/feedback.html', form=form, feedbacks=feedbacks)

@feedback_blueprint.route('/delete_feedback/<int:feedback_id>', methods=['POST'])
def delete_feedback(feedback_id):
    feedback = Feedback.query.get(feedback_id)
    if feedback:
        db.session.delete(feedback)
        db.session.commit()
        flash('Відгук був видалений', 'success')
    else:
        flash('Відгук не знайдено', 'danger')
    return redirect(url_for('.feedback'))

app/todo/__init__.py
from flask import Blueprint

todo_blueprint = Blueprint('todo', __name__, template_folder="templates", url_prefix="/todo")

from . import views

app/todo/views.py
from flask import render_template, redirect, url_for

from app import db
from .forms import TodoForm
from .models import Todo
from . import todo_blueprint

@todo_blueprint.route('/todo', methods=['POST','GET'])
def todo():
    todo_list = Todo.query.all()
    form = TodoForm()
    return render_template("todo/todo.html", todo_list=todo_list, form=form)


@todo_blueprint.route("/add", methods=["POST"])
def todo_add():
    form = TodoForm()
    if form.validate_on_submit():
        title = form.title.data
        new_todo = Todo(title=title, complete=False)
        db.session.add(new_todo)
        db.session.commit()
    return redirect(url_for(".todo"))


@todo_blueprint.route("/update/<int:todo_id>")
def todo_update(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    todo.complete = not todo.complete
    db.session.commit()
    return redirect(url_for(".todo"))


@todo_blueprint.route("/delete/<int:todo_id>")
def todo_delete(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    db.session.delete(todo)
    db.session.commit()
    return redirect(url_for(".todo"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Base {% endblock %} - My Webpage</title>
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% endblock %}
</head>
<body>
{% include "navbar.html" %}
{% block content %}
<h1>{{ current_user.username }}</h1>
{% endblock %}
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
                {% for category, message in messages %}
                    <li class="flash-{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
</div>
{% block body %}

{% endblock %}

{% block js %}
<script src={{url_for('static', filename='js/script.js')}}></script>
{% endblock %}
</body>
</html>

app/templates/feedback.html
{% extends "base.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
    {% endwith %}

    <h1>Залиште свій відгук</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.message.label(class="form-control-label") }}
            {{ form.message(class="form-control") }}
        </div>
        {{ form.submit(class="btn btn-primary") }}
    </form>

    <h2>Всі відгуки</h2>
    <ul>
        {% for feedback in feedbacks %}
            <li>{{ feedback.name }}: {{ feedback.message }}
                <form method="POST" action="{{ url_for('delete_feedback', feedback_id=feedback.id) }}">
                    {{ form.hidden_tag() }}
                    <button class="btn btn-danger">Видалити</button>
                </form>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block body %}
<section id="hero">
    <div class="hero-container" data-aos="zoom-in" data-aos-delay="100">
      <h1>Welcome to INVISIBLE WEBSITE</h1>
      <h2>Viktor Prystai Website</h2>
      <a href="{{ url_for('about') }}" class="btn-get-started">Get Started</a>
    </div>
  </section>
<!-- ======= Footer ======= -->
  <footer id=footer">
    <div class="footer-top">
      <div class="container">

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        <b>Os-name:</b> {{ os_name }}
      </div>
      <div class="credits">
    <b>User Agent:</b> {{ user_agent }}
    <b>Time:</b> {{ current_time }}
      </div>
    </div>
  </footer><!-- End Footer -->
{% endblock %}

app/templates/macros.html
{% macro render_field(field) %}
    <div class="form-group">
        {{ field.label(class="form-label") }}
        {{ field(class="form-control") }}
        {% if field.errors %}
            <ul class="errors">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endmacro %}

app/templates/navbar.html
<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div id="logo">
        <a href="../portfolio/templates/portfolio/home.html"><img src="" alt=""></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto "href="{{ url_for('portfolio.home') }}">Home</a></li>
          <li><a class="nav-link scrollto "href="{{ url_for('portfolio.about') }}">About</a></li>
          <li><a class="nav-link scrollto "href="{{ url_for('auth.login') }}">Log in</a></li>
            <li><a class="nav-link scrollto "href="{{ url_for('auth.register') }}">Register</a></li>
            <li><a class="nav-link scrollto "href="{{ url_for('feedback.feedback') }}">Feedback Form</a></li>
            <li><a class="nav-link scrollto "href="{{ url_for('todo.todo') }}">Todo Form</a></li>
          <li><a class="nav-link scrollto" href="{{ url_for('auth.users') }}">My Profile</a></li>
          <li><a class="nav-link scrollto" href="{{ url_for('auth.logout') }}">Logout</a></li>
          <li class="dropdown"><a href="{{ url_for('post.create_post') }}"><span>Post</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{{ url_for('post.list_posts') }}">List posts</a></li>
                <li><a href="{{ url_for('post.list_categories') }}">List categories</a></li>
{#              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>#}
{#                <ul>#}
{#                  <li><a href="#">Deep Drop Down 1</a></li>#}
{#                  <li><a href="#">Deep Drop Down 2</a></li>#}
{#                  <li><a href="#">Deep Drop Down 3</a></li>#}
{#                  <li><a href="#">Deep Drop Down 4</a></li>#}
{#                  <li><a href="#">Deep Drop Down 5</a></li>#}
{#                </ul>#}
{#              </li>#}
{#              <li><a href="#">Drop Down 2</a></li>#}
{#              <li><a href="#">Drop Down 3</a></li>#}
{#              <li><a href="#">Drop Down 4</a></li>#}
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="{{ url_for('portfolio.skill') }}">My skills</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->

app/templates/register.html
{#{% extends "base.html" %}#}
{##}
{#{% block title %}Register{% endblock %}#}
{##}
{#{% block body %}#}
{#    <div class="container mt-5">#}
{#        <div class="row">#}
{#            <div class="col-md-6 mx-auto">#}
{#                <div class="card">#}
{#                    <div class="card-body text-center">#}
{#                        <h2 class="mb-4">Register</h2>#}
{#                        <form method="POST" novalidate action="{{ url_for('register') }}">#}
{#                            {{ form.hidden_tag() }}#}
{#                            <div class="form-group">#}
{#                                {{ form.username.label(class="form-control-label") }}#}
{#                                <div class="input-group">#}
{#                                    {{ form.username(class="form-control") }}#}
{#                                </div>#}
{#                                {% for error in form.username.errors %}#}
{#                                    <small class="form-text text-danger">{{ error }}</small>#}
{#                                {% endfor %}#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                {{ form.email.label(class="form-control-label") }}#}
{#                                <div class="input-group">#}
{#                                    {{ form.email(class="form-control") }}#}
{#                                </div>#}
{#                                {% for error in form.email.errors %}#}
{#                                    <small class="form-text text-danger">{{ error }}</small>#}
{#                                {% endfor %}#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                {{ form.password.label(class="form-control-label") }}#}
{#                                <div class="input-group">#}
{#                                    {{ form.password(class="form-control") }}#}
{#                                </div>#}
{#                                {% for error in form.password.errors %}#}
{#                                    <small class="form-text text-danger">{{ error }}</small>#}
{#                                {% endfor %}#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                {{ form.confirm_password.label(class="form-control-label") }}#}
{#                                <div class="input-group">#}
{#                                    {{ form.confirm_password(class="form-control") }}#}
{#                                </div>#}
{#                                {% for error in form.confirm_password.errors %}#}
{#                                    <small class="form-text text-danger">{{ error }}</small>#}
{#                                {% endfor %}#}
{#                            </div>#}
{#                            {{ form.submit(class="btn btn-primary btn-block") }}#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block body %}
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div style="width: 300px;">
            <h2 class="mb-4 text-center">Register</h2>
            <form method="POST" novalidate action="{{ url_for('register') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <label for="username" class="form-control-label">Username</label>
                    <div class="input-group">
                        {{ form.username(class="form-control") }}
                    </div>
                    {% for error in form.username.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="email" class="form-control-label">Email</label>
                    <div class="input-group">
                        {{ form.email(class="form-control") }}
                    </div>
                    {% for error in form.email.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="password" class="form-control-label">Password</label>
                    <div class="input-group">
                        {{ form.password(class="form-control") }}
                    </div>
                    {% for error in form.password.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="confirm_password" class="form-control-label">Confirm Password</label>
                    <div class="input-group">
                        {{ form.confirm_password(class="form-control") }}
                    </div>
                    {% for error in form.confirm_password.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                {{ form.submit(class="btn btn-primary btn-block") }}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/skills.html
{% extends "base.html" %}

{% block title %} POSTs {% endblock %}

{% block body %}

<h1>MY SKILLS page</h1>
<ul>
    {% for post in posts %}
    <li>
        <a href="{{ url_for('skill', idx=loop.index - 1) }}"> {{post["exp"]}} : {{post["title"]}}</a>
    </li>
    {% endfor%}
</ul>

{% endblock %}

app/templates/todo.html
{% extends "base.html" %}
{% block body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python Flask Simple To Do - SQLAlchemy</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>

<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-lg-9 col-xl-7">
                    <div class="card rounded-3">
                        <div class="card-body p-4">

                            <h4 class="text-center my-3 pb-3">To Do - SQLAlchemy</h4>

                            <!-- WTForms Form -->
                            <form class="row" method="post" action="{{ url_for('todo_add') }}">
                                {{ form.hidden_tag() }}
                                <div class="col-4">
                                    <div class="form-outline">
                                        {{ form.title(class="form-control", placeholder="Enter a task here") }}
                                    </div>
                                </div>
                                <div class="col-6">
                                    {{ form.submit(class="btn btn-primary") }}
                                </div>
                            </form>

                            <table class="table mb-4">
                                <thead>
                                    <tr>
                                        <th scope="col">No.</th>
                                        <th scope="col">Todo item</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for todo in todo_list %}
                                    <tr>
                                        <th scope="row">{{todo.id }}</th>
                                        <td>{{ todo.title }}</td>
                                        <td>
                                            {% if todo.complete == False %}
                                            <div class="alert alert-secondary" role="alert">In progress</div>
                                            {% else %}
                                            <div class="alert alert-success" role="alert">Completed</div>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="btn btn-success" href="{{ url_for('todo_update', todo_id=todo.id) }}">Update</a>
                                            <a class="btn btn-danger ms-1" href="{{ url_for('todo_delete', todo_id=todo.id) }}">Delete</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>
{% endblock %}

app/templates/users.html
{% extends "base.html" %}
{% from "macros.html" import render_field %}

{% block body %}
    <h2 class="mb-4">Account Information</h2>

    <div>
        <img src="{{ url_for('static', filename='profile_photos/' + current_user.image_file) }}" alt="Фото профілю">
        <p>Username: {{ current_user.username }}</p>
        <p>Email: {{ current_user.email }}</p>

        <h3 class="mt-4">About Me</h3>
        <p>{{ current_user.about_me }}</p>

        <h3 class="mt-4">Last Seen</h3>
        <p>{{ current_user.last_seen.strftime('%Y-%m-%d %H:%M:%S') }}</p>

        <h3 class="title">Change password</h3>
</div>
<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('change_password') }}" id="change_password_form" novalidate>
            {{ change_password_form.csrf_token }}
                {{ render_field(change_password_form.current_password)}}
                {{ render_field(change_password_form.new_password)}}
                {{ render_field(change_password_form.confirm_password)}}
            {{ change_password_form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>
    </div>
</div>

        <h3 class="mt-4">Update profile information</h3>
        <form method="POST" action="{{ url_for('update_users') }}" enctype="multipart/form-data">
            {{ update_form.hidden_tag() }}
            <div class="form-group">
                {{ update_form.username.label(class="form-label") }}
                {{ update_form.username(class="form-control") }}
            </div>
            <div class="form-group">
                {{ update_form.email.label(class="form-label") }}
                {{ update_form.email(class="form-control") }}
            </div>

            <div class="form-group">
                {{ update_form.about_me.label(class="form-label") }}
                {{ update_form.about_me(class="form-control") }}
            </div>
            <div class="form-group">
                {{ update_form.profile_photo.label(class="form-label") }}
                {{ update_form.profile_photo(class="form-control-file") }}
            </div>
            <div class="form-group">
                {{ update_form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock %}